RHeavenStudio/HeavenStudio

- Assets/Scripts/Games/TapTrial/TapTrial.cs
- Assets/Scripts/Minigames.cs
Added Double Tap and Triple Tap placeholder animations so they can be used in a remix until they're made actually playable.
> Added Placeholder animations for Tap Trial

- Assets/Scripts/Games/KarateMan/BarrelDestroyEffect.cs
Now shadows for the Barrel Destroy effect will fade properly
> Karate Man shadows no longer fade to White

- Assets/Scripts/Games/SpaceSoccer/Ball.cs
The soccer ball that is part of the prefab no longer defaults to the Dispensing state (when i refactored the ball script a while ago, i dealt with this problem by just disabling that ball, but this solution should work even with the ball enabled)
> Fixed space soccer ball spawning when it shouldn't be

- Assets/Scripts/Games/Spaceball/SpaceballBall.cs
Swing sound is supposed to play any time the batter swings, even when the ball gets hit, but on autoplay it doesn't.
> (minor) Fix for a sound error with Autoplay in Spaceball

- README.md
Not sure if we want to actually do this, I just wrote some random stuff in for now, since I'm not sure how much we want it to be accessible.
Uses [nightly.link](https://nightly.link/) to automatically retrieve the latest artifacts. Are there better options?
An alternative would be to upload each artifact as a GitHub pre-release release.
> Link GitHub Actions Builds in readme

- .github/workflows/main.yml
GitHub Actions blocks repository secrets containing Unity account info required to successfully run the build workflow, so all PR actions will always fail. Because of this, disable builds on PR to reduce unnecessary action runs.
It might be possible to have the action run after a repository owner approves the PR, but I'm not sure if this allows the PR action to use secrets either. Should be easy to test though
> Disable GitHub Actions build on PR

- Assets/Scripts/LevelEditor/Editor.cs
Also Possibly Fixes #67
The timeline stretching function wasn't called when a remix was imported
> Fix Importing Music files on Linux

- Assets/Scripts/GameCamera.cs
- Assets/Scripts/Games/PajamaParty/CtrPillowMonkey.cs
- Assets/Scripts/Games/PajamaParty/CtrPillowPlayer.cs
- Assets/Scripts/Minigames.cs
- Assets/Scripts/Util/AnimationHelpers.cs
examples in Pajama Party's code
also makes remixes stop when the "end" entity is reached, allows (deprecated) loading of the old camera entities
> Internal: Animation speed helper functions

- Assets/Scripts/Games/CropStomp/CropStomp.cs
- Assets/Scripts/Games/CropStomp/Veggie.cs
- Assets/Scripts/Games/Minigame.cs
- Assets/Scripts/Games/RhythmRally/Paddlers.cs
- Assets/Scripts/Games/RhythmRally/RhythmRally.cs
- Assets/Scripts/Games/RhythmTweezers/Hair.cs
- Assets/Scripts/Games/RhythmTweezers/LongHair.cs
- Assets/Scripts/Games/SpaceSoccer/Ball.cs
- Assets/Scripts/Games/SpaceSoccer/Kicker.cs
- Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs
- Assets/Scripts/Games/Spaceball/SpaceballBall.cs
- Assets/Scripts/Games/WizardsWaltz/Plant.cs
- ProjectSettings/ProjectSettings.asset
Updated the following minigames to use PlayerActionEvent for hit detection:
- Space Soccer
- Spaceball
- Rhythm Rally
- Rhythm Tweezers
- Wizard's Waltz (Mahou Tsukai)
Fixed bug in Crop Stomp where queued inputs would carry over between games switches (technical: PlayerActionEvent objects now clean themselves up on every game switch)
> Second PlayerActionEvent Pass

- Assets/Scripts/Games/Tambourine/Tambourine.cs
- Assets/Scripts/Games/WorkingDough/WorkingDough.cs
- Fix beat intervals being set too early, making some use be unable to be hit
- Clear queued inputs when playback is stopped
- Queue cue sounds in advance to improve timing
- Clear queued inputs when playback is stopped
> Working Dough Fixes

- Assets/Resources/Prefabs/Cameras.prefab
- Assets/Resources/Prefabs/Editor/SettingsMenu/GameSettings.prefab
- Assets/Resources/Prefabs/GameTex.renderTexture
- Assets/Resources/Prefabs/GameTexMaterial.mat
- Assets/Resources/Prefabs/GameTexMaterial.mat.meta
- Assets/Resources/Prefabs/OverlayTex.renderTexture
- Assets/Resources/Prefabs/OverlayTexMaterial.mat
- Assets/Resources/Prefabs/OverlayTexMaterial.mat.meta
- Assets/Scripts/GlobalGameManager.cs
- Assets/Scripts/LevelEditor/SettingsDialog/Tabs/GameSettings.cs
- Assets/Scripts/StaticCamera.cs
- Game overlays can now be positioned off-screen (in the letterbox area) ![image](https://user-images.githubusercontent.com/43734252/224577014-c9aae012-bc2b-40c6-8470-7fba7ee7d27a.png)
- Letterbox and Ambient Glow settings are now shown in the UI Editor preview 
- Resolved issues with transparent objects in the game scene overriding game RenderTexture alpha
> Off-Screen Overlay Support

- Assets/Scripts/InputSystem/PlayerInput.cs
This fixes the bug where no minigame plays, by applying similar strategy to make the keyboard be recognized in macos.
> Playback/ Keyboard Bug Fix

- Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/StringPropertyPrefab.cs
- Assets/Scripts/LevelEditor/Selections.cs
Ctrl-A is correctly blocked from triggering the timeline select all shortcut if a text box is being edited.
> Ctrl-A in textboxes bug

- .gitignore
- Assets/Scripts/Conductor.cs
- Assets/Scripts/LevelEditor/Editor.cs
- Assets/Scripts/Util/Sound.cs
- Assets/Scripts/Util/SoundByte.cs
- Packages/packages-lock.json
- README.md
- SoundByte scheduled sounds won't schedule playback until their time to play is close enough (currently 0.5 seconds before)
- Made conductor `SetBeat()` share same audio seek logic as `Play()`
- Audio offset is applied before playback to the absolute time instead of being "invisibly" applied during calculation of beat position
- Allow AIFF audio files to be imported in editor (let us know if this breaks)
- Added note to readme warning about desync issues with VBR-encoded MP3s (#490)
> Sound Scheduling Improvements

- .github/workflows/build.yml
our actions are currently experiencing issue https://github.com/jlumbroso/free-disk-space/issues/4 where packages fail to be fetched
this follows a workaround until they add their toggle to use an alternative pkg source
> build fail workaround

- Assets/Scripts/Games/AirRally/AirRally.cs
- Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
- Assets/Scripts/Games/CatchyTune/CatchyTune.cs
- Assets/Scripts/Games/CropStomp/CropStomp.cs
- Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs
- Assets/Scripts/Games/FirstContact/FirstContact.cs
- Assets/Scripts/Games/FlipperFlop/FlipperFlop.cs
- Assets/Scripts/Games/GleeClub/GleeClub.cs
- Assets/Scripts/Games/LaunchParty/LaunchParty.cs
- Assets/Scripts/Games/Lockstep/Lockstep.cs
- Assets/Scripts/Games/OctopusMachine/OctopusMachine.cs
- Assets/Scripts/Games/QuizShow/QuizShow.cs
- Assets/Scripts/Games/SeeSaw/SeeSaw.cs
- Assets/Scripts/Games/SeeSaw/SeeSawGuy.cs
- Assets/Scripts/Games/Tambourine/Tambourine.cs
- Assets/Scripts/Games/TapTrial/TapTrial.cs
- Assets/Scripts/Games/TapTroupe/TapTroupe.cs
- Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
Call And Response Games:
- Games that have a signal before the player turn (quiz show, tambourine, second contact) now have stretchable pass turns again.
Lockstep:
- Made force stepping functional with onbeat/offbeat switch blocks
- Added standalone "Hai" and "Ho" blocks
Seesaw:
- Fixed a bug where the camera would not be at position (0, 0) in manual play when sometimes pressing early
Misc:
- Added some more collapseable properties, the ones for crop stomp and catchy tune don't work on my end for some reason, and i have no idea why, maybe it's onedrive? But it definitely feels like it's an issue on my end. Please tell me if they work on ur end
> Misc. Tweaks the tweakquel

- Assets/Scripts/GameManager.cs
Doesn't use WaitForSeconds anymore which can effect performance and adapts to tempo changes now. Also automatically stops the flash when the chart is not playing.
> Black Flash Improvement/Optimisation

- Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs
The issue was that the bg color persistance checking was checking for kitties color entities and not space soccer's. Thus trying to access values that the kitties one doesn't have.
> Space Soccer Going To Black Fix

- Assets/Resources/Games/forkLifter.prefab
- Assets/Resources/Sprites/Games/ForkLifter/Animations/Hand.controller
- Assets/Resources/Sprites/Games/ForkLifter/Animations/Hand_Flick.anim
- Assets/Scripts/Games/AirRally/AirRally.cs
- Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
- Assets/Scripts/Games/CatchyTune/CatchyTune.cs
- Assets/Scripts/Games/CropStomp/CropStomp.cs
- Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs
- Assets/Scripts/Games/FlipperFlop/FlipperFlop.cs
- Assets/Scripts/Games/ForkLifter/ForkLifter.cs
- Assets/Scripts/Games/ForkLifter/ForkLifterHand.cs
- Assets/Scripts/Games/ForkLifter/ForkLifterPlayer.cs
- Assets/Scripts/Games/ForkLifter/Pea.cs
- Assets/Scripts/Games/GleeClub/GleeClub.cs
- Assets/Scripts/Games/KarateMan/KarateMan.cs
- Assets/Scripts/Games/LaunchParty/LaunchParty.cs
- Assets/Scripts/Games/Lockstep/Lockstep.cs
- Assets/Scripts/Games/OctopusMachine/Octopus.cs
- Assets/Scripts/Games/OctopusMachine/OctopusMachine.cs
- Assets/Scripts/Games/QuizShow/QuizShow.cs
- Assets/Scripts/Games/SeeSaw/SeeSaw.cs
- Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs
- Assets/Scripts/Games/TapTrial/TapTrial.cs
- Assets/Scripts/Games/TapTroupe/TapTroupe.cs
- Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs
- Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs
- Assets/Scripts/Minigames.cs
- Assets/Scripts/Util/AnimationHelpers.cs
* you can now cue fork lifter while inactive
* the dreaded fork lifter woosh sfx is fixed
* octopus machine prepare should look better
-i didn't do too much testing with it so feel free to dm me riqs that aren't working with it (if there are any)
internal stuff : 
* DoScaledAnimationFromBeatAsync() is a method that plays an animation as if it was playing on a certain beat
-this is mostly useful for cues or prepares
* you can now access the riqentity through the func of a collapsing property
-i think im gonna keep tinkering with the collapse properties though cuz they could probably be better/more useful
> Collapsing Properties Update + Animation From Beat Method

- Assets/Scripts/GameCamera.cs
- Assets/Scripts/GameManager.cs
- Assets/Scripts/Games/BoardMeeting/BoardMeeting.cs
- Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs
- Assets/Scripts/Games/CheerReaders/CheerReaders.cs
- Assets/Scripts/Games/CropStomp/CropStomp.cs
- Assets/Scripts/Games/FlipperFlop/FlipperFlop.cs
- Assets/Scripts/Games/KarateMan/KarateMan.cs
- Assets/Scripts/Games/Lockstep/Lockstep.cs
- Assets/Scripts/Games/RhythmRally/RhythmRally.cs
- Assets/Scripts/Games/Ringside/Ringside.cs
- Assets/Scripts/Games/Rockers/Rockers.cs
- Assets/Scripts/Games/SeeSaw/SeeSawGuy.cs
- Assets/Scripts/Games/Spaceball/Spaceball.cs
- Assets/Scripts/Games/TapTroupe/TapTroupe.cs
- Assets/Scripts/Games/TapTroupe/TapTroupeZoomOut.cs
- Assets/Scripts/StaticCamera.cs
- Fixed GameCamera.AdditionalPosition being delayed by 1 frame, causing multiple issues including a 1 frame jumpscare when Rhythm Rally and BTSDS are instanced.
- Fixed the viewport values not being applied to the canvas in the onBeatChanged callback
> 3D Camera and Viewport Position Update Fixes

- Assets/Resources/Prefabs/GameView/CamerasEditor.prefab
- Assets/Scripts/Games/AirRally/AirRally.cs
- Assets/Scripts/Games/QuizShow/QuizShow.cs
- Assets/Scripts/Games/SeeSaw/SeeSaw.cs
- Assets/Scripts/Games/Splashdown/NtrSynchrette.cs
- Assets/Scripts/Games/Splashdown/Splashdown.cs
- Assets/Scripts/Games/TossBoys/TossBoys.cs
- Assets/Scripts/Games/TossBoys/TossKid.cs
- Assets/Scripts/Minigames.cs
- Assets/Scripts/ScreenTiling.cs
- Assets/Scripts/StaticCamera.cs
VFX:
- Added new vfx event that "removes" the letterbox by making the game fit your screen (Credit goes to firerise for that mostly)
- Split screen tiling into two events: Tile Screen and Scroll Tiles
Toss Boys:
- Fixed a bug with bops
- Made the game be controlled with tap instead of flick in touch mode
See Saw:
- Fixed bug where landing sound would play after game switch
- See now jumps high up before a high jump like the original
- Made the start jump sound not trigger immediately on game switch if it was supposed to play earlier, then it just is silent
Quiz Show:
- Fixed a bug where the amount of inputs needed would be changed 2 beats before an interval
Splashdown:
- Synchrettes spawned while diving will now enter the world under the water
> Screen Tiling Split into two events + Some tweaks and new vfx!

- Assets/Scenes/Editor.unity
- Assets/Scripts/GameManager.cs
- Assets/Scripts/Games/BlueBear/BlueBear.cs
- Assets/Scripts/Games/GleeClub/ChorusKid.cs
- Assets/Scripts/Games/TossBoys/TossBoys.cs
- Assets/Scripts/Games/TossBoys/TossKid.cs
- Assets/Scripts/Minigames.cs
- Assets/Scripts/StretchCameraVFX.cs
- Assets/Scripts/StretchCameraVFX.cs.meta
VFX:
- Added a new VFX event "Stretch Camera", stretches the game camera (or is an illusion of it). This is useful for combining it with viewport scaling and screen tiling
Blue Bear:
- Fixed Long Emotions freezing up the editor
Glee Club:
- Fixed fade out working really weirdly
Toss Boys:
- Fixed toss kids uncrouching when they should be crouched
> Stretch Camera VFX Event + Fixes

- Assets/Scripts/Games/GleeClub/ChorusKid.cs
- Assets/Scripts/Games/LaunchParty/LaunchPartyRocket.cs
- Assets/Scripts/Games/MeatGrinder/MeatGrinder.cs
- Assets/Scripts/Games/MeatGrinder/MeatToss.cs
- Assets/Scripts/Games/MunchyMonk/MunchyMonk.cs
- Assets/Scripts/Games/OctopusMachine/Octopus.cs
- Assets/Scripts/Games/Ringside/Ringside.cs
- Assets/Scripts/Games/SpaceDance/SpaceDance.cs
- Assets/Scripts/Games/TapTroupe/TapTroupeCorner.cs
- Assets/Scripts/Games/TossBoys/TossKid.cs
- Assets/Scripts/Games/WorkingDough/WorkingDough.cs
- Assets/Scripts/Util/AnimationHelpers.cs
non-devs, pay no attention. nothing was added on the front end.
IsPlayingAnimationName() has been changed to IsPlayingAnimationNames(), and instead of taking a string, it takes in params as an array of strings. the method then checks if the current anim state is in that array, and also checks the stuff it was checking for before.
works well, easier to use, and probably more efficient! what's there to hate
> IsPlayingAnimationName() -> IsPlayingAnimationNames()

- Assets/Scripts/Games/FlipperFlop/FlipperFlop.cs
Should fix #537 by changing the one small thing. It works assuming you don't need to change anything else for these changes (such as a meta file or some other portion that controls it).
There are still other games not sorted at all (at least in the daily builds) but those games seem to be less complete. I hope they are sorted for any releases, though.
> Fix #537 (Flipper Flop chronology)

- Assets/Scripts/Games/AirRally/AirRally.cs
- Assets/Scripts/Games/DoubleDate/DoubleDate.cs
Noon is when the sun is at its peak, bluest sky. The 'golden hour' happens at sunrise or sunset. This PR should make that accurate for Air Rally and Double Date, which both currently have golden skies at 'noon'.
While both of these are sunset and not sunrise in their actual games (Air Rally for some reason skips the sunrise), the fact that there is day and night transitions in Air Rally led me to try and use a word that applies to both sunrise and sunset. For lack of a better one, it's currently called Twilight. However, this can be changed to something better based on how y'all prefer.
> Fix golden hour time of day settings being labelled "noon"

- Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
- Assets/Scripts/Games/MrUpbeat/UpbeatMan.cs
Now you can choose how many blips it takes before the text appears on mr upbeat's dumb forehead instead of being locked to 4 beats
> Upbeat blip length

- Assets/Scripts/Games/Rockers/RockersRocker.cs
This fixes a couple bugs with the rockers pitch bend being inaccurate, especially at different playback speeds.
One thing to note is that this could make older remixes using the pitch bend sound weird because I noticed that inputted semitones in older versions would sometimes be inaccurate:
https://github.com/RHeavenStudio/HeavenStudio/assets/62869918/eead29c9-ece1-462b-aa6e-c19480758f7d
In this clip the bend should be going from C# to F# by bending +5 semitones, but it only sounds correct when bending +4 semitones, this is fixed with this commit though. I don't know what the best solution for this would be to avoid confusing players, but I just wanted to make sure to point it out here.
> Fix Rockers pitch bend
