Assets/Scripts/GlobalGameManager.cs, Assets/Scripts/LevelEditor/Timeline/TempoTimelineObj.cs, Assets/Scripts/Minigames.cs
The tempo change still doesn't work right if you start in the middle of a remix, but you shouldn't be stopped from placing one down anymore.
=> Fixed tempo change tool not working

Assets/Scenes/Editor.unity, Assets/Scripts/GameManager.cs, Assets/Scripts/LevelEditor/Editor.cs
Allows you to call GameManager.LoadRemix("") to initialize a blank remix at bpm 120. The New button (or CTRL+N) calls Editor.NewRemix();
=> Added New (CTRL+N) Button

Assets/Scripts/LevelEditor/Editor.cs
I'm the big dumb (so i added it now)
=> Whoops I never added CTRL+N (Button worked but shortcut didn't)

Assets/Scripts/LevelEditor/Timeline/Timeline.cs
=> Added Autoplay and Metronome Hotkeys

Assets/Scripts/Minigames.cs
Fixed the issues with my fork so you can merge this safely now :)
=> Fixed the "sigh" SFX in Fork Lifter

Assets/Scripts/EventCaller.cs, Assets/Scripts/GameManager.cs
The way it was set up before was really weird. It should be better now.
=> Fixed event caller

Assets/Scripts/Games/KarateMan/KarateMan.cs
=> Fixed a typo in the Karate Man Background names

Assets/Resources/Games/rhythmRally.prefab, Assets/Scripts/Games/RhythmRally/RhythmRally.cs, Assets/Scripts/Minigames.cs
Rotate the camera with different easing functions and the option to add/remove from current rotation.
=> Added Camera Events to Rhythm Rally

Assets/Scripts/Games/ForkLifter/Pea.cs
The commit looks a lot larger than it is. I just wrapped it all in an if statement. This'll prevent a fork that can accumulate infinite peas without gulping
=> Fork now only holds up to 4 peas in Fork Lifter

Assets/Scripts/Games/SpaceSoccer/Kicker.cs
(You can still use X in case you already had the muscle memory)
=> You can now Press and Release Z for high-kick-toe

Assets/Scripts/Games/ClappyTrio/ClappyTrio.cs, Assets/Scripts/Minigames.cs
You can select between 1-8 lions and the code for spacing them evenly is a lot nicer and less brute-forced
=> Added "Change Lion Count" event to Clappy Trio

Assets/Scripts/Beatmap.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/Games/PlayerActionObject.cs, Assets/Scripts/Games/SpaceSoccer/Kicker.cs, Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs, Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs, Assets/Scripts/Minigames.cs, Assets/Scripts/PlayerInput.cs
So now you can disable inputs if you need to :)
=> Added Checkbox Parameter + Toggle Inputs Event

Assets/Scenes/Editor.unity, Assets/Scripts/Games/KarateMan/KarateMan.cs, Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/GridGameSelector.cs, Assets/Scripts/Minigames.cs
Merged pot+rock+ball+tacobell into "hit", merged hit3 and 4 into hit3, and merged bgfxon and bgfxoff to "set background fx".
Despite these changes, previous charts will work just fine as the previous events still exist but are hidden in the editor
=> Merged all the events in Karate Man + Fixed The Toggle Input Bug

Assets/Scenes/Editor.unity, Assets/Scripts/Games/DJSchool/DJSchool.cs, Assets/Scripts/Games/ForkLifter/ForkLifter.cs, Assets/Scripts/Minigames.cs, Assets/Scripts/SoundEffects.cs, Assets/Scripts/SoundEffects.cs.meta
Merged Count-in events, Fork Lifter events, Clappy Trio events, and added an "ooh" toggle to DJ School :)
=> Editor Event Cleanup Pass

Assets/Resources/Games/karateman.prefab, Assets/Resources/Sprites/Games/KarateMan/karateman_main.png.meta, Assets/Scripts/Games/KarateMan/CookingPotDestroyEffect.cs, Assets/Scripts/Games/KarateMan/CookingPotDestroyEffect.cs.meta, Assets/Scripts/Games/KarateMan/KarateJoe.cs, Assets/Scripts/Games/KarateMan/KarateMan.cs, Assets/Scripts/Games/KarateMan/Pot.cs, Assets/Scripts/Minigames.cs
=> Added Cooking Pot, Alien, and Pot hit stars to Karate Man

Assets/Scripts/Games/WizardsWaltz/Wizard.cs, Assets/Scripts/Games/WizardsWaltz/WizardsWaltz.cs
Based on megaminerjenny's suggestions :)
=> Wizard's Waltz height fix + position based on start interval

Assets/Resources/Sprites/Games/MrUpbeat/Animations/Fall.anim, Assets/Resources/Sprites/Games/MrUpbeat/Animations/Step.anim
Less interpolated but cleaner as a result
=> Cleaned up Mr. Upbeat's animations

Assets/Scripts/Beatmap.cs, Assets/Scripts/Games/DrummingPractice/Drummer.cs, Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs, Assets/Scripts/Minigames.cs
=> Drumming Practice: ability to set each Mii Character separately

Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs, Assets/Scripts/Games/MrUpbeat/UpbeatStep.cs
=> Mr. Upbeat now starts on the go no matter what

Assets/Resources/Games/drummingPractice.prefab, Assets/Scripts/Games/DrummingPractice/Drummer.cs, Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs, Assets/Scripts/Minigames.cs
=> Added Streaks and Set Background Color to Drumming Practice

Assets/Scripts/LevelEditor/Timeline/TempoTimeline.cs
UNTESTED
you asked for this lmao
=> Editor: disabled tempo change placing

Assets/Scripts/Games/ClappyTrio/ClappyTrio.cs, Assets/Scripts/Games/CropStomp/CropStomp.cs
i could've sworn i tested the recent pr before making it, but i guess not
=> fixing bugs from previous pr

Assets/Scripts/Games/BlueBear/BlueBear.cs, Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs, Assets/Scripts/Games/ClappyTrio/ClappyTrio.cs, Assets/Scripts/Games/CropStomp/CropStomp.cs, Assets/Scripts/Games/DJSchool/DJSchool.cs, Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs, Assets/Scripts/Games/FanClub/FanClub.cs, Assets/Scripts/Games/Fireworks/Fireworks.cs, Assets/Scripts/Games/ForkLifter/ForkLifter.cs, Assets/Scripts/Games/KarateMan/KarateMan.cs, Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs, Assets/Scripts/Games/RhythmRally/RhythmRally.cs, Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs, Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs, Assets/Scripts/Games/Spaceball/Spaceball.cs, Assets/Scripts/Games/TapTrial/TapTrial.cs, Assets/Scripts/Games/WizardsWaltz/WizardsWaltz.cs, Assets/Scripts/Minigames.cs
moved minigame declarations outside of Minigames.cs using reflection
=> Internal: separate minigame definitions

Assets/Scripts/GameCamera.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/Games/Spaceball/Spaceball.cs, Assets/Scripts/Minigames.cs
=> Global Camera Movement

Assets/Scripts/Conductor.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/LevelEditor/Timeline/TempoTimeline.cs, Assets/Scripts/LevelEditor/Timeline/Timeline.cs
needs testing but all past issues related to tempo changes *should* be fixed
=> Tempo changes restored

Assets/Scripts/Games/Minigame.cs
What is this, JSDoc :stuck_out_tongue:?
=> Fix ScheduleInput docstring

Assets/Plugins/Color picker/ColorPicker Material.mat, Assets/Scenes/Editor.unity, Assets/Scripts/GlobalGameManager.cs, Assets/Scripts/LevelEditor/Commands/Block.cs, Assets/Scripts/LevelEditor/DisableSelectOnHover.cs, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs, Assets/Scripts/LevelEditor/SettingsDialog/DispAudioSettings.cs, Assets/Scripts/LevelEditor/SettingsDialog/DispAudioSettings.cs.meta, Assets/Scripts/LevelEditor/SettingsDialog/SettingsDialog.cs, Assets/Scripts/LevelEditor/Timeline/Timeline.cs, Assets/Scripts/LevelEditor/Timeline/TimelineEventObj.cs, ProjectSettings/ProjectSettings.asset
=> Editor Bugfixes and Display Settings

Assets/Scripts/InputSystem/ControllerTypes/InputJoyshock.cs, Assets/Scripts/InputSystem/InputController.cs, Assets/Scripts/LevelEditor/SettingsDialog/Tabs/ControllerSettings.cs, Assets/Scripts/Util/BitwiseUtils.cs
- (untested) add support for playstation controllers' lightbar
- fix issues with feature flags
=> Controllers Support Update 1

Assets/Resources/Games/launch party.prefab
So I updated the launch party prefab. The launchpad is now visible and stars extend past the default window.
=> Launch Party Prefab Update

Assets/Scripts/Beatmap.cs, Assets/Scripts/Games/KarateMan/KarateMan.cs
oi mate thats a lotta events ya got there, want me to clean em up for ya?
i dont know how it would happen but by god we need array-based properties
=> added shadow type to set bg effects

Assets/Scripts/Games/ClappyTrio/ClappyTrio.cs, Assets/Scripts/Games/KarateMan/KarateMan.cs
clappy trio clap is 1 beat
joe object colors are now default correct
=> Misc adjustments

Assets/Scripts/GameCamera.cs, Assets/Scripts/Minigames.cs
its a lil smooth at lower intensities but it works! lots of "complicated" "math" going on here.
thanks for all the help, minenice!
recommended settings -
intensity: 2
length: 0.25
=> Screen shake event (VFX)

Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs
=> Random code refactoring

Assets/Scripts/BeatmapFormats/DynamicBeatmap.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/LevelEditor/Editor.cs
Due to some recent discoveries about a certain upcoming rhythm game, I have added support for unrecognized entities found in remix.json to be loaded, moved, and saved.
=> Unrecognized entity support

.github/workflows/main.yml, BUILD.md, README.md
Also improved build instructions and corrected some stuff in the readme.
=> Compress the prebuilt binaries as tar

Assets/Scripts/GameManager.cs, Assets/Scripts/Games/ClappyTrio/ClappyTrioPlayer.cs, Assets/Scripts/Games/CropStomp/Farmer.cs, Assets/Scripts/Games/DJSchool/DJSchool.cs, Assets/Scripts/Games/FanClub/NtrIdolFan.cs, Assets/Scripts/Games/KarateMan/KarateManJoe.cs, Assets/Scripts/Games/Lockstep/Lockstep.cs, Assets/Scripts/Games/MarchingOrders/MarchingOrders.cs, Assets/Scripts/Games/Minigame.cs, Assets/Scripts/Games/PajamaParty/CtrPillowPlayer.cs, Assets/Scripts/Games/PlayerActionEvent.cs, Assets/Scripts/Games/PlayerActionObject.cs, Assets/Scripts/Games/RhythmSomen/RhythmSomen.cs, Assets/Scripts/Games/RhythmTweezers/LongHair.cs, Assets/Scripts/Games/SamuraiSliceNtr/NtrSamuraiObject.cs, Assets/Scripts/Games/Tambourine/Tambourine.cs
- Chart playback now keeps track of an accuracy score in the background, this will be used for future features (overlays such as Skill Star and Timing Display.)
=> Scoring System Preparation

README.md
We are now under @RHeavenStudio !!
=> Change links in the README.md

Assets/Scripts/GameManager.cs, Assets/Scripts/Games/Spaceball/Spaceball.cs, Assets/Scripts/Minigames.cs
One beat before a ball is pitched in Spaceball, the "dispenser" auto prepares.
Added `preFunctionLength` to `GameAction`, which dictates how many beats `preFunction` should be called before `function`.
=> Auto Spaceball Dispense

Assets/Scripts/Conductor.cs, Assets/Scripts/LevelEditor/Timeline/Timeline.cs, Assets/Scripts/Util/Sound.cs
- Minigames can now modify song pitch in their scripts
=> Expose Song Pitch to Minigames

Assets/Resources/Games/sneakySpirits.prefab, Assets/Resources/Sprites/Games/SneakySpirits/Animations/Move.anim, Assets/Resources/Sprites/Games/SneakySpirits/Animations/MoveDown.anim, Assets/Resources/Sprites/Games/SneakySpirits/Animations/Tree Stationary.controller, Assets/Resources/Sprites/Games/SneakySpirits/Animations/Tree Stationary.controller.meta, Assets/Resources/Sprites/Games/SneakySpirits/Animations/Tree.anim, Assets/Resources/Sprites/Games/SneakySpirits/Animations/TreeSlow.anim, Assets/Resources/Sprites/Games/SneakySpirits/Animations/TreeSlow.anim.meta, Assets/Scripts/Games/SneakySpirits/SneakySpirits.cs, Assets/Scripts/Games/SneakySpirits/SneakySpiritsGhost.cs
- Spirits now bob smoothly, like Tengoku
- Spirits now correctly only appear on a beat, not beforehand
- Tree now stops during slowdowns
- Second animation frame of tree realigned
=> Sneaky Spirits Visual Fixes

Assets/Scripts/Games/TrickClass/TrickClass.cs
exactly what the title says, suggested by Mizuno on the discord server
=> Trick on the class: Speech Bubble Toggle

Assets/Resources/Prefabs/GameTex.renderTexture
=> re-enable stencil buffer in game RenderTexture

Assets/Resources/Sprites/Games/TapTrial/Animations/Monkey/monkey_jump_tap/tap/final/FinalJumpTap.anim
unity deleted the frames of the animation idk why Sorry
=> Fixed Final Jump Tap

Assets/Scripts/LevelEditor/Editor.cs
Reverts RHeavenStudio/HeavenStudio#356
=> Revert "Remove duplicate song saving"

Assets/Scripts/Games/CheerReaders/CheerReaders.cs, Assets/Scripts/Util/Jukebox.cs
Fix Cheer Readers audio bug
Add code doc to Jukebox
=> Implement proper way of getting audio clip length

Assets/Scripts/GameManager.cs, Assets/Scripts/Minigames.cs
=> gameswitch flash toggle

Assets/Scenes/Editor.unity, Assets/Scripts/LevelEditor/EventSelector/GridGameSelector.cs
The currentEventIndex will no longer change when another UI element is in front of it.
=> Event Selection Menu Bug

Assets/Resources/Games/dogNinja.prefab, Assets/Resources/Games/meatGrinder.prefab, Assets/Resources/Sprites/Games/DogNinja/DogNinjaBackground.png.meta, Assets/Resources/Sprites/Games/MeatGrinder/Animations/Boss/BossIdle.anim, Assets/Scripts/Games/DJSchool/DJSchool.cs, Assets/Scripts/Games/DogNinja/DogNinja.cs, Assets/Scripts/Games/DogNinja/ThrowObject.cs, Assets/Scripts/Games/MeatGrinder/MeatGrinder.cs, Assets/Scripts/Games/MeatGrinder/MeatToss.cs, Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs, Assets/Scripts/Games/MrUpbeat/UpbeatMan.cs, Assets/Scripts/Games/MunchyMonk/MunchyMonk.cs, Assets/Scripts/Games/TapTrial/TapTrial.cs
* fixed #271
* fixed the "ooh" being unchecked in dj school to break the cue
* fixed meat grinder. as a whole. (i.e start interval being yucky and weird)
* added d-pad to meat grinder (thank u seanski 🙏)
* fixed different objects using only one cut sound in dog ninja
-still retains the ability to play only one sound when they're the same object
* finally made dog ninja objects be able to be started outside of the game
-you can mute them as well, but only when they're inactive
* added toggle to prepare in dog ninja
* readded the inactive beeping to mr upbeat
-i will be reworking that game pretty soon tho btw
* fixed dumplings showing up early in munchy monk
-im working on that game rn but i wanted to fix it cause it was pretty integral to the game
-the cause was preFunctionLength being set …
=> Bug Fixes + Small Additions

Assets/Scripts/Games/SeeSaw/SeeSaw.cs
I really hope this is the last time someone finds something extremely gamebreaking with see saw today lol
=> See Saw works properly on game switch and does the proper start jump now

Assets/Scripts/GameManager.cs, Assets/Scripts/Games/CropStomp/CropStomp.cs, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/Minigames.cs
fixes #461 
fixes #420 
fixes #408 
fixes unreported bug where loading charts with no music would show an error (this is now silent but shows a warning in the log)
=> make base datamodels for special entity reading

Assets/Scripts/Minigames.cs
inferred riqs with unset tempo default to 120 bpm
=> Don't infer the track field when importing converted v0 riq coming from unknown origin

Assets/Scripts/GameInitializer.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/Minigames.cs, Assets/Scripts/UI/PauseMenu.cs, Packages/packages-lock.json
- update Jukebox to version 0.1.3
- fixes for inferred entity loading
- discontinued importing .tengoku and .rhmania files
- fixes #468
=> Jukebox Package Update

Assets/Resources/Games/rhythmTweezers.prefab, Assets/Resources/Games/workingDough.prefab, Assets/Scripts/Games/CallAndResponseHandler.cs, Assets/Scripts/Games/RhythmTweezers/Hair.cs, Assets/Scripts/Games/RhythmTweezers/LongHair.cs, Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs, Assets/Scripts/Games/RhythmTweezers/Tweezers.cs, Assets/Scripts/Games/Rockers/Rockers.cs, Assets/Scripts/Games/WorkingDough/NPCDoughBall.cs, Assets/Scripts/Games/WorkingDough/WorkingDough.cs
=> CNR API Internal Rework

Assets/Resources/Games/firstContact.prefab, Assets/Scripts/Games/FirstContact/FirstContact.cs, Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs, Assets/Scripts/Games/Rockers/Rockers.cs, Assets/Scripts/Games/WorkingDough/WorkingDough.cs
Second Contact has been entirely reworked internally, only difference the user may notice is that auto pass turn and ellipses are a thing now.
Working Dough and Rockers don't use the CNR API anymore, but rhythm tweezers still does.
All devs should only use the CNR API in very niche cases.
=> Second Contact Rework + Small CNR API changes

Assets/Resources/Games/quizShow.prefab, Assets/Scripts/Games/QuizShow/QSTimer.cs, Assets/Scripts/Games/QuizShow/QSTimer.cs.meta, Assets/Scripts/Games/QuizShow/QuizShow.cs, Assets/Scripts/Games/Tambourine/Tambourine.cs
That should be all call and response games except meat grinder which i reworked on another branch.
=> Quiz Show and Tambourine Reworks

Assets/Scripts/Games/SneakySpirits/SneakySpirits.cs
Fixed a bug where the ghosts would not appear close to game switch
=> Sneaky Spirits Fix

Assets/Scripts/GameManager.cs
reword the unknown origin message to be less menacing
=> Undefined chart origin no longer crashes the program

Assets/Resources/Games/tramAndPauline.prefab
whoever made the particle destroy itself as the stop action, i'll find you
=> Tram and pauline second jump not working fixed

Assets/Scripts/Games/BuiltToScaleDS/BuiltToScaleDS.cs, Assets/Scripts/Games/CoinToss/CoinToss.cs, Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs, Assets/Scripts/Games/ForkLifter/ForkLifter.cs, Assets/Scripts/Games/Kitties/Kitties.cs, Assets/Scripts/Games/Lockstep/Lockstep.cs, Assets/Scripts/Games/OctopusMachine/OctopusMachine.cs, Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs, Assets/Scripts/Games/SeeSaw/SeeSaw.cs, Assets/Scripts/Games/SpaceDance/SpaceDance.cs, Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs, Assets/Scripts/Games/Tambourine/Tambourine.cs, Assets/Scripts/Games/TossBoys/TossBoys.cs
All games that have BG Color change events now work the same way: Persistant through game switches with an ease option, just like flashes basically lol
this was tedious as fuck
All devs please follow this when making bg color changes or similar visual events
=> Background Color Change Parity

Assets/Resources/Games/seeSaw.prefab, Assets/Scripts/Games/SeeSaw/SeeSawGuy.cs, Assets/Scripts/Games/TapTroupe/TapTroupe.cs, Assets/Scripts/Games/TheDazzles/TheDazzles.cs
- Added an option to mute the cheering sound in The Dazzles
- Added an option to mute the ready cue in Tap Troupe
- Fixed the camera being jittery in See-Saw
=> Misc. Tweaks and Fixes part 1 googleplex

Assets/Scripts/Games/Rockers/Rockers.cs, Assets/Scripts/Games/SeeSaw/SeeSaw.cs
- Fixed auto pass turn in rockers making the sound play on next switch to rockers
- Fixed not being able to get the frogs to jump again after a string of jumps in See Saw
=> Rockers + See Saw fix

Assets/Scripts/Games/SpaceSoccer/SpaceSoccer.cs, Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs, Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/BoolPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/ColorPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/EnumPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NumberPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/StringPropertyPrefab.cs, Assets/Scripts/Minigames.cs
The system behind adding collapseable properties is now done! Now we just need to add them where applicable, let me know if you have any ideas for this.
Only Space Soccer has them now as an example, check that game's script on how it works. But to roughly explain it allows you turn on or off multiple parameters based on a condition, like the color being red or the number being 0 etc.
=> Collapseable Properties Functionality

Assets/Scripts/Conductor.cs, Assets/Scripts/EventCaller.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/InputSystem/PlayerInput.cs, Assets/Scripts/Minigames.cs
- fix lag spike when starting playback from the middle of a chart
- considerably reduce garbage generation in GameManager
=> Chart Seek Bugfix

Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs
fixes the ding not stopping the stepping at the right time
=> Quick Mr. Upbeat Fix

Assets/Scripts/Util/Sound.cs
Allows changing the volume over time linearly of non one-shot sounds without killing them.
=> LerpVolume Function

Assets/Resources/Prefabs/Common/RightClickDropdown.prefab, Assets/Resources/Prefabs/Common/RightClickDropdown.prefab.meta, Assets/Scenes/Editor.unity, Assets/Scripts/Games/CatchyTune/CatchyTune.cs, Assets/Scripts/GlobalGameManager.cs, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs, Assets/Scripts/LevelEditor/EventSelector/EventPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/BoolPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/ColorPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/EnumPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/NumberPropertyPrefab.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/StringPropertyPrefab.cs, Assets/Scripts/UI/LeftClickTMP_Dropdown.cs, Assets/Scripts/UI/LeftClickTMP_Dropdown.cs.meta, Assets/Scripts/UI/RightClickDropdownObject.cs, Assets/Scripts/UI/RightClickDropdownObject.cs.meta
=> Reset Event Property Value + Right Click Dropdown API + Confirm Quit

Assets/Resources/Sprites/Games/KarateMan/karateman_cellshader.mat, Assets/Scripts/Games/FanClub/FanClub.cs, Packages/manifest.json, Packages/packages-lock.json
=> fan club thing and recorder package

Assets/Scripts/Games/Global/Filter.cs, Assets/Scripts/Minigames.cs
Filters are executed based on the track now (top to bottom)
Filters also work like flashes do now
=> Filter Rework

Assets/Resources/Games/blueBear.prefab, Assets/Resources/Sprites/Games/BlueBear/Animations/Breakup.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Breakup.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/BreakupExit.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/BreakupExit.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback0.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback0.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback0Exit.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback0Exit.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback1.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback1.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback1Exit.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback1Exit.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback2.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback2.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback2Exit.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback2Exit.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback3.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback3.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback3Exit.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback3Exit.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/NoStory.anim, Assets/Resources/Sprites/Games/BlueBear/Animations/NoStory.anim.meta, Assets/Resources/Sprites/Games/BlueBear/Animations/Story.controller, Assets/Resources/Sprites/Games/BlueBear/Animations/Story.controller.meta, Assets/Scripts/Games/BlueBear/BlueBear.cs, Assets/Scripts/Games/BlueBear/Treat.cs
- Added Blue Bear Story Events
- Fixed a bug with inputs not being disabled in OnDestroy
- Made donuts/cakes be able to be used outside of Blue Bear
=> Blue Bear Story + Tweak/Fixes

Assets/Scripts/Games/Global/Filter.cs, Assets/Scripts/Minigames.cs, Assets/Scripts/ScreenTiling.cs
- Filters now use slots instead of the tracks
- Fixed a bug where screen tiling would cause the game view to become smaller
=> Screen Tiling Bug Fix + Filter Slots

Assets/Resources/Sprites/Games/BlueBear/Animations/Flashback0Exit.anim, Assets/Resources/Sprites/Games/SeeSaw/Animation/Guy/Jump_OutOut_Fall.anim, Assets/Scripts/Conductor.cs, Assets/Scripts/Games/BlueBear/BlueBear.cs, Assets/Scripts/Games/BlueBear/Treat.cs, Assets/Scripts/Games/BoardMeeting/BoardMeeting.cs, Assets/Scripts/Games/CatchyTune/CatchyTune.cs, Assets/Scripts/Games/CheerReaders/CheerReaders.cs, Assets/Scripts/Games/DJSchool/DJSchool.cs, Assets/Scripts/Games/DJSchool/Student.cs, Assets/Scripts/Games/DogNinja/DogNinja.cs, Assets/Scripts/Games/DoubleDate/DoubleDate.cs, Assets/Scripts/Games/DrummingPractice/DrummingPractice.cs, Assets/Scripts/Games/FanClub/FanClub.cs, Assets/Scripts/Games/KarateMan/KarateMan.cs, Assets/Scripts/Games/MeatGrinder/MeatGrinder.cs, Assets/Scripts/Games/Minigame.cs, Assets/Scripts/Games/MunchyMonk/MunchyMonk.cs, Assets/Scripts/Games/OctopusMachine/OctopusMachine.cs, Assets/Scripts/Games/RhythmRally/RhythmRally.cs, Assets/Scripts/Games/RhythmSomen/RhythmSomen.cs, Assets/Scripts/Games/Ringside/Ringside.cs, Assets/Scripts/Games/SamuraiSliceNtr/SamuraiSliceNtr.cs, Assets/Scripts/Games/SeeSaw/SeeSawGuy.cs, Assets/Scripts/Games/SpaceDance/SpaceDance.cs, Assets/Scripts/Games/TapTrial/TapTrial.cs, Assets/Scripts/Games/TheDazzles/TheDazzles.cs, Assets/Scripts/Games/TossBoys/TossBoys.cs, Assets/Scripts/Games/TrickClass/TrickClass.cs
Blue Bear:
- Fixed emotions being weird sometimes
- Fixed date story being odd in position
Tap Trial:
- Giraffe no longer jumpscares when missing jump tap
See Saw:
- See now plays appropiate animations for high jumps
General:
- Internally reworked how auto bops are handled so issues like something not auto bopping immediately or not being deactivated for a beat are fixed now
- Fixed a bug where the metronome would stack up metronome sounds until enabling the metronome again
=> Auto Bop Internal Rework + Bug Fixes

Assets/Resources/Games/trickClass.prefab
- make Trick on the Class less jank with perspective changes
=> Trick on the Class prefab adjustment

Assets/Resources/Prefabs/GameView/GameTex.renderTexture, Assets/Resources/Prefabs/GameView/OverlayTex.renderTexture, Assets/Scenes/Editor.unity, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/LevelEditor/EditorTheme.cs, Assets/Scripts/LevelEditor/Timeline/Timeline.cs, Assets/Scripts/LevelEditor/TooltipGiver.cs, Assets/Scripts/LevelEditor/TooltipGiver.cs.meta
Tooltips can now be added by adding the TooltipGiver script to any GameObject as a component.
=> Replace hardcoded Tooltip.AddTooltip() calls with TooltipGiver script in GameObject

Assets/Scripts/TitleManager.cs
First PR for heaven studio
Impatient people can now skip the logo animation by pressing any button
=> Title screen logo skip

Assets/Scenes/Editor.unity, Assets/Scripts/Games/RhythmRally/RhythmRally.cs, Assets/Scripts/GlobalGameManager.cs, Assets/Scripts/InputSystem/PlayerInput.cs, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/LevelEditor/EventSelector/PropertyPrefabs/ColorPropertyPrefab.cs, Assets/Scripts/LevelEditor/RemixPropertiesDialog/PropertyPrefabs/EnumChartPropertyPrefab.cs, Assets/Scripts/LevelEditor/RemixPropertiesDialog/Tabs/ChartInfoProperties.cs, Assets/Scripts/Minigames.cs, Assets/Scripts/TitleManager.cs
- implement additive camera angle
- fix issues with various easing types not being clamped
- fix angle not wrapping around
- certain key shortcuts now exit fullscreen
- colour picker hex input now disable shortcuts properly
- fix issues with control style property dropdown
- implement #597
- increase max queued frames
- remove older platform-specific controller compatibility logic
=> Small Fixes

Assets/Scripts/Games/ClappyTrio/ClappyTrio.cs, Assets/Scripts/Games/KarateMan/KarateMan.cs, Assets/Scripts/Games/KarateMan/KarateManNoriController.cs, Assets/Scripts/Games/RhythmTweezers/RhythmTweezers.cs
fixed the block properties being weird + put fxType back into background appearance (though it's still also in gameplay modifiers)
gameplay modifiers now persist across gameplay switches! ill probably revert this if people don't like it, tho
added a toggle for sfx in the clappy trio sign too
=> Some Karate Man Fixes

Assets/Scripts/EventCaller.cs, Assets/Scripts/GameManager.cs, Assets/Scripts/LevelEditor/Editor.cs, Assets/Scripts/LevelEditor/EventSelector/EventParameterManager.cs, Assets/Scripts/LevelEditor/Timeline/Timeline.cs, Assets/Scripts/LevelEditor/Timeline/TimelineEventObj.cs, Assets/Scripts/Minigames.cs
I have ZERO clue as to why we haven't done this two years ago
also removes the last (redundant) uses of the `Split(int)` extension method
this is an experimental change that can be reverted if there are problems
=> Put Minigame Definitions in a Dictionary

Assets/Scripts/Games/FirstContact/FirstContact.cs
https://github.com/RHeavenStudio/HeavenStudio/assets/67805443/110b985e-462e-42e4-9f3c-e6315a045991
New line parameter allows you to reset the textbox and erase previous text, works on any amount in an interval and does not erase fail text/semi-fail text
=> Newline breaks in Second Contact

Assets/Resources/Games/mrUpbeat.prefab, Assets/Resources/Sprites/Games/MrUpbeat/Animations/UpbeatAnims/FallL.anim, Assets/Resources/Sprites/Games/MrUpbeat/Animations/UpbeatAnims/FallR.anim, Assets/Resources/Sprites/Games/MrUpbeat/Animations/UpbeatAnims/Idle.anim, Assets/Resources/Sprites/Games/MrUpbeat/Animations/UpbeatAnims/Step.anim, Assets/Scripts/Games/DogNinja/DogNinja.cs, Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs, Assets/Scripts/Games/MrUpbeat/UpbeatMan.cs
mr upbeat letter would flip. i originally forgot to test it with anything but A and W 😭 
dog ninja bop cancelling fixed, just needed an anim check
might do more but this is probably my last pr for a very long time! hope r1 goes well :)
=> Last Minute R1 Fixes

Assets/Resources/Games/launchParty.prefab, Assets/Resources/Sprites/Games/LaunchParty/Animations/Flashing.anim, Assets/Resources/Sprites/Games/LaunchParty/Animations/Glare.controller, Assets/Resources/Sprites/Games/LaunchParty/Animations/Glare.controller.meta, Assets/Resources/Sprites/Games/Rockers/Animations/JJMiss.anim, Assets/Resources/Sprites/Games/Rockers/Animations/JJMissComeOn.anim
miss animations in rockers were swapped, made launch party bg less ugly
=> Launch party bg / Rockers miss fix

README.md
this should show up on `release_1_patches`
=> [style] Update README.md (test new action)

.github/workflows/cherry-tirage.yml, Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs, Assets/Scripts/Games/MunchyMonk/MunchyMonk.cs
this is the correct branch. right?
* mr upbeat input fix
* munchy monk blush fix
=> just two bug fixes

Assets/Resources/Sprites/Games/Kitties/kittiesSprites.png.meta
=> Kitties Resprite

Assets/Scripts/Games/ForkLifter/ForkLifter.cs, Assets/Scripts/Games/ForkLifter/ForkLifterPlayer.cs, Assets/Scripts/Games/ForkLifter/Pea.cs
oops... the burger eat sfx never played.
fixed that + added a choice to manually select which sfx you want
=> fork lifter burger fix

Assets/Scripts/Games/Manzai/Manzai.cs
updates old boing blocks to new boing blocks
assigns numbers to the elements in the enum so that it will stay backwards compatible :D
=> Boing Updater + Enum Fix

Assets/Scripts/Games/BonOdori/BonOdori.cs
man.
PSA to new coders!! check your code before you pr it.
=> mssing semicolon

Assets/Scripts/Games/Cannery/Cannery.cs
fix inactive cues + bg block check
small oversight, crazy how "- 2" and a single variable can literally stop the game from working
=> Cannery Hotfix

Assets/Scripts/Games/RapMen/RapMen.cs
=> Hide Rap Men

Assets/Scripts/Games/ForkLifter/ForkLifter.cs, Assets/Scripts/Games/MrUpbeat/MrUpbeat.cs, Assets/Scripts/Games/SpaceDance/SpaceDance.cs, Assets/Scripts/Games/Tambourine/Tambourine.cs
* fix space dance and tambourine backgrounds
* fix mr upbeat importing
=> R1.1 Hotfixes
